name: Deploy to Amazon EBS

on:
  push:
    branches:
      - deploy-EBS
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest  
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: 'ap-northeast-1' 
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          application_name: ebs-deployment
          environment_name: Ebs-deployment-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-670968082947
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy.zip
