name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - new-branch-for-ebs

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'ap-northeast-1'

      - name: Configure AWS Elastic Beanstalk CLI
        run: |
          eb --version  # Check the Elastic Beanstalk CLI version
          eb init -p 'docker running on 64bit Amazon Linux 2023' -r 'ap-northeast-1' 'ebs-deployment' # Initialize Elastic Beanstalk CLI

      - name: Build and push Docker image to AWS ECR
        run: |
          $(aws ecr get-login --no-include-email --region ap-northeast-1)
          docker build -t react-app-image .
          docker tag react-app-image:latest 670968082947.dkr.ecr.ap-northeast-1.amazonaws.com/react-app-image:latest
          docker push 670968082947.dkr.ecr.ap-northeast-1.amazonaws.com/react-app-image:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy Ebs-deployment-env2# Deploy your application to Elastic Beanstalk
